site_name: PSS Cookbook
site_description: Usage for PSS Language
site_author: Luther Lee
copyright: Copyright &copy; 2023 Luther Lee
repo_url: https://github.com/LeeKaiXuan/PSS_Cookbook
edit_uri: blob/main/docs/
repo_name: LeeKaiXuan/PSS_Cookbook

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
    view: material/eye

  features:
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  status:
    New: New
    Stable: Stable
    WIP: Work-In-Progress

extra_css:
  - includes/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - includes/tablesort.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: True
      auto_append:
        - 'docs/includes/abbreviations.md'
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - search

nav:
  - Home: 'index.md'
  - Data Types:
    - DataTypes/index.md
    - Integer Types: 'DataTypes/IntegerTypes.md'
  - Operator:
    - Operator/index.md
    - Binary Bitwise: 'Operator/BinaryBitwise.md'
    - Primary Expressions: 'Operator/Expressions.md'
  - Collections:
    - Array: 'Collections/Arrays.md'
    - List: 'Collections/Lists.md'
    - Map: 'Collections/Maps.md'
    - Set: 'Collections/Sets.md'
  - Procedural:
    - Procedural/index.md
  - Traversal:
    - Traversal/index.md

not_in_nav:
  includes/
