site_name: PSS CookBook
site_description: Usage for PSS Language
site_author: Luther Lee
copyright: Copyright &copy; 2023 - 2023 Luther Lee
repo_url: https://github.com/LeeKaiXuan/PSS_CookBook
edit_uri: blob/main/docs/
repo_name: LeeKaiXuan/PSS_CookBook

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
    view: material/eye

  features:
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  status:
    New: New
    Stable: Stable
    WIP: Work-In-Progress

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: True
      auto_append:
        - 'docs/includes/abbreviations.md'
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - search

nav:
  - Home: 'index.md'
  - Data Types:
    - DataTypes/index.md
    - Numeric Types: 'DataTypes/NumericTypes.md'
  - Operator:
    - Operator/index.md
    - Primary Expressions: 'Operator/Expressions.md'
  - Array:
    - Array/index.md
    - Operators: Array/Operators.md
    - Methods: Array/Methods.md
  - List:
    - List/index.md
    - Operators: List/Operators.md
    - Methods: List/Methods.md

not_in_nav:
  includes/
